# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "terraform/test/"
      - "terraform/staging/"
      - "terraform/production/"
    schedule:
      interval: "weekly"
    groups:
      terraform-providers:
        group-by: dependency-name
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
